name: Run My Node.js Blog Website

on:
  push:
    paths:
      - 'New-Blog-Website/**'
    branches: [main]

jobs:
  build-nodejs-app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: New-Blog-Website

    steps:
      - name: Checkout
        uses: actions/checkout@v6.1.0
      - name: Setup Node.js
        uses: actions/setup-node@v6.5.0
        with:
          node-version: 25.x
      - name: Install dependencies
        run: npm install
      - name: Start App
        run: npm start
      
  
